### ISSUE TITLE
Is it possible to Show the SUM on grid Load instead of selecting Manually ?

### ISSUE THREAD

**Issue by Ranjitsingh** [mehrgithub/dcrmeg#10]
Really appreciate your efforts for this wonderful grid functionality. 
I've one question, Is it possible to Show the SUM on grid Load instead of selecting Manually ? 

I mean when the grid loads (during form load) i would like to show the SUM by default instead the user is clicking on Aggregate button and choose SUM option. 

Thanks in Advance.

**Comment by mehrgithub** [comment]
Hi,

Currently, it is not possible to persist aggregates. However, I will be adding this as a configurable option in the next release (work  in progress).

Regards,
Mehrdad

**Comment by NeilRenwick** [comment]
Hi. Thanks so much for all you work on the grid, it's been extremely useful in our CRM system. The aggregate function is great but it would be useful if it was more configurable so rather than just applying a blanket 'Allow aggregates' setting you can choose which column you want to allow aggregates on and preset the aggregate type for the column. Appreciate this is no doubt easier said than done.

**Comment by mehrgithub** [comment]
Hi,

Unfortunately, I can't remove the 'Allow Aggregates' option. It could break other users who rely on this option.

However, as per your suggestion, I have added the option to preset the aggregate type for a numeric field in the configuration. The grid will use this to display and auto update aggregate value for the target field.

I have also added the functionality to the grid to auto update aggregate values that were not preset (manually invoked using the aggregate button menu) in the configuration (after an update, delete, and clone operations).

I am finishing up with the the addition of Web API, sticky headers and footer, ... The new release should be ready in about a week.

Thank you,
Mehrdad

**Comment by NeilRenwick** [comment]
That all sounds absolutely fantastic Mehrdad, thank you so much. I look forward to trialling the new version when released.

**Comment by mehrgithub** [comment]
Hi,

Please download the new version and let me know if the new functionality is working properly.

https://github.com/mehrgithub/dcrmeg/releases

Thank you,
Mehrdad

**Comment by NeilRenwick** [comment]
Thanks for the changes Mehrdad, the new functionality seems absolutely great from my testing so far. It really is a brilliant grid. Top work!!!

**Comment by Ranjitsingh** [comment]
Hi Mehrdad,

I was giving a try in Dynamics 365, but editable grid configuration webpage is unalbe to load. 

Any idea ? I’m getting Invalid XML Code 500 error.

 

Thanks,

Ranjit

**Comment by mehrgithub** [comment]
Hi Ranjit,

I just tested the configuration and the grid in 365 (on premise, API version 8.2) again and I am not getting the error you have reported.

Would you be to go to Networking tab of the developer tools and find the server error's response and post it here (should be in JSON format)?

Thank you,
Mehrdad
