### ISSUE TITLE
DCRM Grid after D365 V9 Upgrade

### ISSUE THREAD

**Issue by ArneHuse** [mehrgithub/dcrmeg#11]
First of all, thank you for all your work on this awesome tool! One of my clients went with an early update to the new version of D365 Online (V9.0) and the DCRM Grids are all blank. I cannot create a new grid either. I am just noting this issue as a "heads up" to DCRM Grid users contemplating an early update.

**Comment by mehrgithub** [comment]
Download and install the latest version (1.0.6.8) which is compatible with D365 V9.

https://github.com/mehrgithub/dcrmeg/tree/master/solutions/Dynamics365%20Online%20Ver%201612%20(9.0.0.3172)

**Comment by ArneHuse** [comment]
You da' man! That worked beautifully, thank you!
