### ISSUE TITLE
 issue with window.parent.DCrmEgGridOnload

### ISSUE THREAD

**Issue by hjmhyl** [mehrgithub/dcrmeg#11]
Hi mehrgithub,
Thank you for developing such a greate editable grid.
I was trying to use JavaScript Callbacks functionality to make one column in the editable grid read-only based on particular CRM security role, that column data type is OptionSet.
After I done the setup and use window.parent.DCrmEgGridOnload=DCrmEgGridOnload to disable each field in that column, everything works except that user can still select the last option in the optionset and save the field. see below screenshot

![6-06-2017 9-16-55 am](https://cloud.githubusercontent.com/assets/18730267/26807436/c378b500-4a99-11e7-8d71-4179e8f8aa7f.png)

below is the DCrmEgGridOnload method

    DCrmEgGridOnload: function (data, entityinfo) {
            data.Option.readonly = !ISADMIN;
    },

Could you please have a look when you get a chance?

**Comment by mehrgithub** [comment]
Hi,

Thank you for reporting this issue in detail. I will take a look.

Mehrdad

**Comment by hjmhyl** [comment]
@sunjuan1409 the problem with your fix is that user can still select the empty option and save.
I think add a another for loop is a better solution, see below:

 readonly: false });  **`};for (var i = 0; i < $editor.optionsData.length; i++) {`** if (window.parent.DCrmEgGridOnload) { callbackData.Option = $editor.optionsData[i];

**Comment by mehrgithub** [comment]
Hi,

Please download the new version and let me know if the issue is resolved.

https://github.com/mehrgithub/dcrmeg/releases

Thank you,
Mehrdad

**Comment by hjmhyl** [comment]
Hi mehrgithub,

Thank you for the new release, I have checked this issue is resolved after install v1.0.6.0.
I noticed that the column width doesn't change anymore no matter what value I put into the Width setting, is this by design?

**Comment by mehrgithub** [comment]
Hi hjmhyl,

I will have a new release in the next few days to hopefully correct this issue along with some resizing issues:

1. Add an option to the configuration to set the minimum width of the columns. Default 15 px.
2. Resize the grid when the size of the container window changes.
3. If a column width is specified in the configuration, it will be used as long as it is not less than the minimum column width specified in the configuration.

Thank you,
Mehrdad
