### ISSUE TITLE
Error while loading the page

### ISSUE THREAD

**Issue by kkodd** [mehrgithub/dcrmeg#14]
I am getting the following:

Unable to load the grid data due to exceptions:
Status Code:500 Generic SQL error.

Unable to add any new record.

**Comment by mehrgithub** [comment]
What version of CRM?
Do you have any plugin(s) that runs when this type of record is created?

**Comment by kkodd** [comment]
Thank you for your help.
I’ve just downloaded the latest version of you plugin and it has worked.
I am using D365 for Sales.

Regards,

Rana Ibrahim
Projects Manager

[cid:image002.jpg@01D3D1A9.C7C63410]

Achrafieh, Sodeco, Beydoun Street, Tueny Bldg 4709
PO BOX 13-5509, T +961 1 426 706,  www.kkodd.co<http://www.kkodd.co/>

This email is confidential.  If you are not the intended recipient, you must not disclose or use the information contained in it.  If you have received this email in error, please tell us immediately by return mail and delete the document.
Be Green -  Please consider the environment before printing this email.
