### ISSUE TITLE
Javascript callback Question

### ISSUE THREAD

**Issue by san-86** [mehrgithub/dcrmeg#15]
Hello, 
in the documentation of your JavaScript callbacks you write the following:
**DCrmEgGridRowOnload Fires for every row to be rendered. Allows setting a field (cell) to readonly and change the background and forground colors.**

Is there a special reason why the field have to be set to readonly before the colors can be be changed ?

**Comment by mehrgithub** [comment]
Hi,

The field doesn't need to be set to readonly to change the colors. Each option can be set desperately without the need to set the others.

Hope this answered your question.

Mehrdad

**Comment by san-86** [comment]
Thank you for the Clarification :-)
