### ISSUE TITLE
Filtered lookup on value from another field in Grid

### ISSUE THREAD

**Issue by tziegner** [mehrgithub/dcrmeg#16]
Hi,

Would it be possible to setup a 'filtered' LookUp based on the value from another field in a grid?  For example, we need the ability to filter a lookup of Contact records based on the value of another field that is in the grid.  If user changes that other field value, then the filtered LookUp will need to change accordingly.  Is this possible somehow, perhaps through JavaScript?

**Comment by mehrgithub** [comment]
Hi,

Currently, this functionality isn't available. However, I can implement a pre query JS call back for the grid lookups which should give you the opportunity to add your own filters/conditions. Similar to "DCrmEgGridOnBeforeFetchRecords" JS call back which allows additional conditions to be added to the fetch XML prior to fetching data for the grid.

Please let me know.

Thank you,
Mehrdad

**Comment by evismara** [comment]
Hi,
is it possible to know which grid is the caller of method DCrmEgGridOnBeforeFetchRecords?
in my scenario i have two grids, in the same form, configured on the same entity.
i need to set different filter, based on the value of different fields of the form.

**Comment by mehrgithub** [comment]
Hi evismara,

Please download and import the new release. https://github.com/mehrgithub/dcrmeg/releases

Added an option to the configuration to allow using a grid custom identifier (GridCustomIdentifier) for each grid. The custom identifier is passed to all the JS call backs. This is for cases where multiple grids exist on the same form and a need to identify originating grid for each the JS call back. Please see [JS call backs documentation](https://github.com/mehrgithub/dcrmeg/blob/master/docs/JavaScript%20Callbacks.md) for examples.

Pleas let me know if the addition of Grid Identifier has resolved your issue.

Thank you,
Mehrdad

**Comment by evismara** [comment]
Hi mehrgithub,
it works.
thanks for quickly response.
