### ISSUE TITLE
Configuration Record does not display list of entities

### ISSUE THREAD

**Issue by tjasonMayo** [mehrgithub/dcrmeg#17]
Dynamics 365 Online version 1612 (8.2.1.207)
Imported the DCRMEditableGrid_1_0_6_0_managed.zip solution and attempted to create a new D CRM EG Configuration record; the "Display grid on entity" dropdown is blank, and the console indicates **Failed to load resource: the server responded with a status of 500 (Internal Server Error)**

Same error using Chrome or IE

//this is the xml errorcode returned from  [/api/data/v8.2/dcrmeg_dcrmegtranslations?fetchXml=%253Cfetch%2520version=%271.0%27%2520output-format=%27xml-platform%27%2520mapping=%27logical%27%2520distinct=%27false%27%253E%253Centity%2520name=%27dcrmeg_dcrmegtranslation%27%253E%253Cattribute%2520name=%27dcrmeg_dcrmegtranslationid%27%2520/%253E%253Cattribute%2520name=%27dcrmeg_name%27%2520/%253E%253Cattribute%2520name=%27dcrmeg_lcid%27%2520/%253E%253Cattribute%2520name=%27dcrmeg_widthisautocalculated%27%2520/%253E%253Cattribute%2520name=%27dcrmeg_width%27%2520/%253E%253Cattribute%2520name=%27dcrmeg_systemfields%27%2520/%253E%253Cattribute%2520name=%27dcrmeg_selectedgridheaders%27%2520/%253E%253Cattribute%2520name=%27dcrmeg_selectfields%27%2520/%253E%253Cattribute%2520name=%27dcrmeg_relatedentitylookup%27%2520/%253E%253Cattribute%2520name=%27dcrmeg_readonly%27%2520/%253E%253Cattribute%2520name=%27dcrmeg_maxrecordsperpage%27%2520/%253E%253Cattribute%2520name=%27dcrmeg_fieldsontheform%27%2520/%253E%253Cattribute%2520name=%27dcrmeg_displaysumfornumericvalues%27%2520/%253E%253Cattribute%2520name=%27dcrmeg_displayonlyrelatedrecords%27%2520/%253E%253Cattribute%2520name=%27dcrmeg_displaygridonentity%27%2520/%253E%253Cattribute%2520name=%27dcrmeg_displaydatafromentity%27%2520/%253E%253Cattribute%2520name=%27dcrmeg_customfields%27%2520/%253E%253Cattribute%2520name=%27dcrmeg_allfields%27%2520/%253E%253Cattribute%2520name=%27dcrmeg_targetentityisrequiered%27%2520/%253E%253Cattribute%2520name=%27dcrmeg_entitytodisplaythegridonisrequiered%27%2520/%253E%253Cattribute%2520name=%27dcrmeg_atleasetonefieldmustbeselected%27%2520/%253E%253Cattribute%2520name=%27dcrmeg_fieldcondition%27%2520/%253E%253Cattribute%2520name=%27dcrmeg_fieldvalue%27%2520/%253E%253Cattribute%2520name=%27dcrmeg_setcondition%27%2520/%253E%253Cattribute%2520name=%27dcrmeg_configcancel%27%2520/%253E%253Cattribute%2520name=%27dcrmeg_removecondition%27%2520/%253E%253Corder%2520attribute=%27dcrmeg_name%27%2520descending=%27false%27%2520/%253E%253Cfilter%2520type=%27and%27%253E%253Ccondition%2520attribute=%27dcrmeg_lcid%27%2520operator=%27eq%27%2520value=%271033%27%2520/%253E%253C/filter%253E%253C/entity%253E%253C/fetch%253E](url)

```
{
  "error":{
    "code":"","message":"Invalid XML.","innererror":{
      "message":"Invalid XML.","type":"System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Microsoft.Xrm.Sdk, Version=8.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]","stacktrace":"   at Microsoft.Crm.Extensibility.OrganizationSdkServiceInternal.RetrieveMultiple(QueryBase query, CorrelationToken correlationToken, CallerOriginToken callerOriginToken, WebServiceType serviceType, Boolean checkAdminMode)\r\n   at Microsoft.Crm.Extensibility.OData.CrmODataExecutionContext.RetrieveMultiple(QueryBase query)\r\n   at Microsoft.Crm.Extensibility.OData.CrmODataServiceDataProvider.ExecuteQueryForEntitySet(CrmODataExecutionContext context, String entitySetName, CustomQueryOptions queryOptions, String fetchXml)\r\n   at Microsoft.Crm.Extensibility.OData.CrmODataServiceDataProvider.RetrieveEdmEntityCollection(CrmODataExecutionContext context, String entityCollectionName, String castedEntityName, ODataQueryOptions queryOptions)\r\n   at Microsoft.Crm.Extensibility.OData.EntityController.GetEntitySet(String entitySetName)\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
    }
  }
}
```

**Comment by mehrgithub** [comment]
Hi,

Thank you for reporting this issue. Please download and import the new release which contains a fix for this bug.

https://github.com/mehrgithub/dcrmeg/releases

Please let me know if the issue has been resolved.

Thank you,
Mehrdad

**Comment by tjasonMayo** [comment]
It works! Thanks so much.

**Comment by tjasonMayo** [comment]
Mehrdad, I’m a little confused about using the script callback functions to dynamically update fields (like calculations, etc.); is there an object model to interact with the grid and set/update values? I tried updating one of the fields {rowdata.Fields[i].Value} in the GridRowOnload event, but I didn’t see the changes in the UI. Also, would it be possible to dynamically filter the lookups? I need one filtered on a form field, and the other filtered based on the relationship to the first…I really love what you’ve done with the grid, but without that feature we won’t be able to meet our client requirements. ☹

Thanks, much appreciated!
