### ISSUE TITLE
Shift Tab to focus on previous field not working

### ISSUE THREAD

**Issue by farcasclaudiu** [mehrgithub/dcrmeg#18]
While editing in grid, Shift+Tab keys used usually on standard forms/grids to focus on previous field not working. Instead it acts as a simple Tab.

**Comment by farcasclaudiu** [comment]
Alson, it seems that pressing Tab Key is changing the boolean values (I don't expect the value to be changed by Tab key while jumping from field to field).

**Comment by mehrgithub** [comment]
Hi,

Please see the new release and let me know if the issue is resolved.

https://github.com/mehrgithub/dcrmeg/releases

Thank you,
Mehrdad
