### ISSUE TITLE
Keyboard friendly selection from option set

### ISSUE THREAD

**Issue by farcasclaudiu** [mehrgithub/dcrmeg#19]
While pressing Tab key in the editable grid, when I reach an option set field, the dropdown shows up and enlist the filtered possible values to select from.
It would be nice if we could select one of the presented options by using arrows keys (up, down), but without triggering the filter as we still need to see available options.

Best regards,
Claudiu

**Comment by mehrgithub** [comment]
Hi,

Please see the new release and let me know if the issue is resolved.

https://github.com/mehrgithub/dcrmeg/releases

Thank you,
Mehrdad
