### ISSUE TITLE
Keep focus after update

### ISSUE THREAD

**Issue by fmainzer** [mehrgithub/dcrmeg#20]
Hi,
we do 

-- a calculation of VAT (VAT field = Amount * vat rate)
-- Setting an invoice position text field based of the value of the article that is selected using a lookup in the row 

We do this with a plugin on presave. To get the values on the grid we need to refresh after save of the grid. Then we loose the Focus.

any sugesstion to solve this?

thx

frank

**Comment by mehrgithub** [comment]
Hi,

Please see the new release and let me know if the issue is resolved.

https://github.com/mehrgithub/dcrmeg/releases

Thank you,
Mehrdad
