### ISSUE TITLE
AutoRefresh after AutoSave does not properly update the grid when Lookup fields change

### ISSUE THREAD

**Issue by farcasclaudiu** [mehrgithub/dcrmeg#21]
AutoRefresh after AutoSave does not properly update the grid when Lookup fields change.

We have a plugin that triggers (pre-operation) when a lookup field changes.
After autosave and autorefresh the grid (UI) is not properly updated (some numeric fields that we process in the plugin).
If we manually press the refresh button the grid gets properly updated.
Any idea how to overcome this issue?

Best regards,
Claudiu

**Comment by tjasonMayo** [comment]
Having same issue updating fields in pre-op plugin do not display new values. Also need a way to set  dynamic lookup filter criteria. Thanks.

**Comment by mehrgithub** [comment]
Hi,

Please see the new release "Auto refresh delay" configuration option and pre fetch lookup JS callback. Please let me know if the issue is resolved.

https://github.com/mehrgithub/dcrmeg/releases

Thank you,
Mehrdad
