### ISSUE TITLE
Unable to create new custom entity record inline with Dynamics 365 Online v1612 (8.2.1.207)

### ISSUE THREAD

**Issue by tjasonMayo** [mehrgithub/dcrmeg#25]
POST https://xxx.crm.dynamics.com/api/data/v8.2/xxx_customentity 400 (Bad Request)
SdkWebAPI.create	@	dcrmeg_webapisdk:61
CreateInlineRecord	@	dcrmeg_dcrmeg:8132
(anonymous)		@	dcrmeg_dcrmeg:7269
dispatch		@	dcrmeg_jquery2:3
r.handle		@	dcrmeg_jquery2:3

**Comment by farcasclaudiu** [comment]
I confirm this is also happening on our project with version 1.0.6.1.
The urderlying error (seen with fiddler or F12) is like this:
"An undeclared property 'mysolution_invoicerecieved_mysolution_invoiceincoming' which only has property annotations in the payload but no property value was found in the payload. In OData, only declared navigation properties and declared named streams can be represented as properties without values."
And one article describing this behavior:
https://exptechsolutions.blogspot.com/2017/06/know-how-set-lookup-value-on.html
It has to do with using CRM WebApi on different CRM versions. We are using v8.2of webapi andwe have this issue.
As a temporary workaround we switched back to version 1.0.5.8 which I think is using either SOAP calls or a more compatible "webapi" sdk.
We're looking forward for a fix on this issue.

Best regards,
Claudiu

**Comment by MikeKo365** [comment]
same for me, I am using Dynamics 365 and the same issue appears,
When can we expect an update on the below.

Thank you very much for your cooperation.
Best Regards,
Mike

**Comment by mehrgithub** [comment]
Hi,

Please see the new release and let me know if the issue is resolved.

https://github.com/mehrgithub/dcrmeg/releases

Thank you,
Mehrdad
