### ISSUE TITLE
Can't select an entity on setup

### ISSUE THREAD

**Issue by jhutjens** [mehrgithub/dcrmeg#26]
After installing the solution I want to create a new "D CRM EG Configuration" record. But the field "Display grid on entity" does not give any enities to select. I am on the latest Dynamics 365 version. What am I doing wrong? Thanks in advance!

Kr,

Jeroen

**Comment by tjasonMayo** [comment]
I had the same issue with CRM Online; be sure you download and import the latest version 1.0.6.1 and you are signed into CRM with admin privileges.

**Comment by jhutjens** [comment]
That was it, thanks!
