### ISSUE TITLE
Parent Id not set on new child record from Window

### ISSUE THREAD

**Issue by tjasonMayo** [mehrgithub/dcrmeg#27]
Creating a new record via the grid using the **window** setting opens the new child entity form, but the parent entity's id is not set on the child record, so it is not related correctly.

**Comment by mehrgithub** [comment]
Hi,

I can't re produce this issue. I did test using custom and system entities using Dynamics 365.

Is the behavior the same in IE and Chrome/FF?

Thank you,
Mehrdad

**Comment by mehrgithub** [comment]
No response, closing this issue.
