### ISSUE TITLE
Unable to load grid data - 400 Error in query syntax

### ISSUE THREAD

**Issue by sunjuan1409** [mehrgithub/dcrmeg#29]
We just installed 1.0.6.2 version (previously on 1.0.5.4) and now every grid throws the following error:
![image](https://user-images.githubusercontent.com/9888707/27806111-4764e568-5ffe-11e7-9712-053455708ee0.png)
"Unable to load the grid data due to exceiptions: Status Code:400 Bad Request - Error in query syntax"

I traced the source code down to this function: SdkWebAPI.retrieveMetadataByLogicalName and it is the uri constructed in the function that throws the error message:
![image](https://user-images.githubusercontent.com/9888707/27806201-d21ff01c-5ffe-11e7-93bd-83437aa454cc.png)

Note: Our CRM version is 8.1.1.1005 (CRM 2016). I don't think this retrieving-by-name capability was added until 8.2.

**Comment by sunjuan1409** [comment]
SdkWebAPI.create is also broken. We cannot create any inline record by clicking "+" button in any grids. The error message says "Cannot read property 'xxx' of undefined". Here 'xxx' sometimes says "value", sometimes says "optionsData", other times says "logicalName". It varies from grid to grid.

**Comment by mehrgithub** [comment]
Hi,

Thank you for reporting this bug. I will have a fix in the next few days.

Mehrdad

**Comment by mehrgithub** [comment]
Hi,

Please download and import the new release v1.0.6.3.

https://github.com/mehrgithub/dcrmeg/releases

I am closing this issue. Please let me know if the issue hasn't been resolved so I can re open the issue.

Thank you,
Mehrdad
