### ISSUE TITLE
Duplicate Items on subgrid & Item lookups

### ISSUE THREAD

**Issue by njegenene** [mehrgithub/dcrmeg#31]
Thanks for the great product. I have the latest version but have a few issues as follows:

1. The subgrid replicates products across all unique records (entities), when you save a set of products for one record, it duplicates the same products on all the other saved records, when you delete, it also deletes on all records.

2. I'd like to be able to lookup products which already have a fixed price and then populate them on the subgrid, thereafter add various quantities per product and do a total of each and a final total at the bottom row.

See the attached screenshots for further details. (Notice the subgrids have similar data)

<img width="861" alt="del1" src="https://user-images.githubusercontent.com/18233881/27865050-b4639d70-6199-11e7-9c18-289cf4da8e71.PNG">
<img width="861" alt="del2" src="https://user-images.githubusercontent.com/18233881/27865051-b46c20bc-6199-11e7-9828-a8b3916d1fb1.PNG">

**Comment by mehrgithub** [comment]
Hi,

I believe your scenario is similar to the one from this question https://github.com/mehrgithub/dcrmeg/issues/30

I can offer two suggestions to display different sets of data for each grid from the same "Product or Service" entity based a/many condition(s). Example, "having a fixed price"

1. You can use field conditions from the Grid configuration. And you aren't limited to only the fields on the grid.

Please see the Field Conditions documentation page:
https://github.com/mehrgithub/dcrmeg/blob/master/docs/Field%20Conditions.md

2. You can use "DCrmEgGridOnBeforeFetchRecords" JavaScript call back to add additional conditions to the fetch XML prior to fetching data for the grid.

For "DCrmEgGridOnBeforeFetchRecords", please see JavaScript Callbacks documentation page:
https://github.com/mehrgithub/dcrmeg/blob/master/docs/JavaScript%20Callbacks.md

I hope this answered your question.

Thank you,
Mehrdad
