### ISSUE TITLE
Unable to get property 'optionsData' of undefined or null reference

### ISSUE THREAD

**Issue by sunjuan1409** [mehrgithub/dcrmeg#33]
To follow up with Closed #29:
We are still having trouble creating new inline records by clicking "+" button. The error message is shown below:
![image](https://user-images.githubusercontent.com/9888707/27871320-f0041cda-616a-11e7-9af3-380f27183f0e.png)

Also in the config record the metadata of the picklist field is blank:
![image](https://user-images.githubusercontent.com/9888707/27871450-4bb4da24-616b-11e7-95e2-73866c89cb9a.png)
"Set Condition" is not working either (not populating the options when clicking "...").

It appears this only happens to global option sets.
Again we are on 8.1.1.1005 on premise.

**Comment by mehrgithub** [comment]
Thank you for reporting this issue. You are correct, the query was missing a reference to global option sets.

I should have a fix ready by tomorrow.

Thank you,
Mehrdad

**Comment by mehrgithub** [comment]
Hi,

Please download and import the new release v1.0.6.4.

https://github.com/mehrgithub/dcrmeg/releases

I did test this in 2016 as best as I could considering limited time and resources available to me. I thank you for your patience and will try to fix any bugs as fast as humanly possible.

I am closing this issue. Please let me know if the issue hasn't been resolved so I can re open it.

Thank you,
Mehrdad
