### ISSUE TITLE
Lookup field is required but no default value was present

### ISSUE THREAD

**Issue by sunjuan1409** [mehrgithub/dcrmeg#34]
![image](https://user-images.githubusercontent.com/9888707/27871923-cd9f4776-616c-11e7-8bb4-a855cb7d6e8e.png)

Our current version (1.0.5.4) allows required lookup field to be blank during inline create. The newer version gives the above error message.

**Comment by mehrgithub** [comment]
This was a reported bug and had to be fixed.

If you need to allow required lookup field to be blank during inline create, an option can be added to configuration to by pass the validation logic. Example, "Allow blank required fields during in line create". Please let me know.

Thank you,
Mehrdad

**Comment by sunjuan1409** [comment]
Yes, sir! A configuration like that would be great!

**Comment by mehrgithub** [comment]
Hi,

Please download and import the new release v1.0.6.5.

https://github.com/mehrgithub/dcrmeg/releases/tag/v1.0.6.5

I am closing this issue. Please let me know if the issue hasn't been resolved so I can re open the issue.

Thank you,
Mehrdad
