### ISSUE TITLE
Regarding Bundle child products

### ISSUE THREAD

**Issue by udaymohan** [mehrgithub/dcrmeg#35]
Hi ,

We are Using DCRM Editable Grid. Its a very helpful one.
We need Bundle Child Products not to bind to Grid.(Hide) Can you pls help with this

**Comment by mehrgithub** [comment]
Hi,

I don't understand what you mean by "Bundle Child Products not to bind to Grid".

Could you please explain your scenario and what you are trying to do and which part do you need help with. I will try to help if I can.

Thank you,
Mehrdad

**Comment by udaymohan** [comment]
Hi,

Thanks for your Quick Response. I will provide details to you, Please let me know if you still not get.

In our Project we are binding products to the DCRM Grid, while we are adding Bundle Products its product family members are also adding with price $0.00.

In “dcrmeg_dcrmeg” JavaScript we tried to restrict those product bundle(option set 3) by commenting value 3 but we can’t stop adding them to grid.


 


Iam adding only one product to Grid but after refreshing its showing total 3 products.

Please find below image Yellow highlighted are duplicates:




Regards,
Uday K

**Comment by mehrgithub** [comment]
Hi Uday K,

Thank you for the explanation. 

Could you please post an image of the grid configuration. Also, the image that you mentioned in your message isn't displaying. Please fix the link for it.

What CRM version are you using?

Thank you,
Mehrdad
