### ISSUE TITLE
Access to grid data in DCrmEgGridOnBeforeLookupFetchRecords

### ISSUE THREAD

**Issue by tjasonMayo** [mehrgithub/dcrmeg#37]
The callback is great for filtering a lookup on static values (although it seems to ignore the filtering condition in the native CRM lookup dialog that displays when you click "Lookup more records"), but I need to filter a lookup based on the value of another lookup (or optionset) in the grid. Is there any way to get to the other field data in the current row when the callback fires, like add a rowdata parameter? Thanks for all your hard work on this!

**Comment by mehrgithub** [comment]
Hi,

I will try to add the means to retrieve the grid data in the next release.

Thank you,
Mehrdad

**Comment by mehrgithub** [comment]
Hi,

Please download and import the new release v1.0.6.5.

https://github.com/mehrgithub/dcrmeg/releases/tag/v1.0.6.5

I have also included a fix for the grid not refreshing after save (Refresh after save configuration option) when updating a single lookup field.

I am closing this issue. Please let me know if the issue hasn't been resolved so I can re open the issue.

Thank you,
Mehrdad
