### ISSUE TITLE
Field Updated in Pre-Operation Sync Plugin not refreshed after Lookup on Auto-Save

### ISSUE THREAD

**Issue by tjasonMayo** [mehrgithub/dcrmeg#38]
Changing a lookup value in the grid fires a sync plugin that recalculates other numeric fields, but the values do not appear until the grid refresh button is clicked manually (I added a 10ms Auto Refresh Delay and tested in IE and Chrome). Changes to non-lookup fields fire and update correctly. Thanks.

**Comment by mehrgithub** [comment]
Thank you for letting us know.

Mehrdad

**Comment by tjasonMayo** [comment]
Actually this is a bug as changing a lookup with autosave doesn't refresh the grid properly...
