### ISSUE TITLE
rowData missing parameter , v 1.0.6.5

### ISSUE THREAD

**Issue by san-86** [mehrgithub/dcrmeg#40]
In JavaScript function function DCrmEgGridRowOnload(rowData, entityinfo), the rowData object had a field called "RowBackgroundColor" , this does not seem to work anymore.

**Comment by mehrgithub** [comment]
I can't re produce this issue. the parameter is working as intended. CRM 2013

rowData.RowBackgroundColor = '#CCCCCC';

How are you setting this parameter? color names, rgb, ...

Thank you,
Mehrdad

**Comment by san-86** [comment]
I'm Using the color name in this example 'LightGrey'

**Comment by san-86** [comment]
I found the Problem, this issue can be closed, Thank you
