### ISSUE TITLE
Disable Grid

### ISSUE THREAD

**Issue by tjasonMayo** [mehrgithub/dcrmeg#41]
Is there a way to disable the entire grid (i.e. add new row and edit existing rows) on the form for an inactive record such as a Won Opportunity? Thanks.

**Comment by tjasonMayo** [comment]
Through testing I saw that the grid **does** disable automatically on an inactive record (when it is refreshed); is there a way to do the same programatically?

**Comment by mehrgithub** [comment]
I will add a DisableGrid API so the grid can be set to read-only using JS, similar to GridData and RefreshGrid. I will also fix the inconsistency.

Thank you,
Mehrdad

**Comment by tjasonMayo** [comment]
Awesome! I did not know about the GridData and RefreshGrid APIs...is there documentation somewhere for those?

**Comment by mehrgithub** [comment]
New release:
https://github.com/mehrgithub/dcrmeg/releases/tag/v1.0.6.6

[Grid API documentation (Accessing grid data, ...)](https://github.com/mehrgithub/dcrmeg/blob/master/docs/GridApi.md)
