### ISSUE TITLE
Export to Excel

### ISSUE THREAD

**Issue by acraigx** [mehrgithub/dcrmeg#7]
My users LOVE this feature BUT they are asking if there's a way to modify the functionality so that it exports ALL of the data in the grid, not just the current page.  I'm not sure why a user would ever want to only export one page of data.

**Comment by mehrgithub** [comment]
Please download and import the latest solution (DCRMEditableGrid_1_0_5_8_managed.zip) from the solutions directory.

Now all the records are exported from the grid. Please note that exporting thousands of records will take some time. Exporting 12000 accounts to Excel from CRM running on a VM with limited resources (one CPU, 4 GB ram) took approximately 10 seconds.

Thank you,
Mehrdad

**Comment by acraigx** [comment]
Thank you, thank you, thank you!
